# Generated by Django 2.0.3 on 2018-04-29 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeTract',
            fields=[
                ('tract_id', models.IntegerField(primary_key=True, serialize=False)),
                ('income', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteLocation',
            fields=[
                ('epa_id', models.IntegerField(primary_key=True, serialize=False)),
                ('formatted_address', models.TextField(blank=True, max_length=155)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zipcode', models.IntegerField(blank=True)),
                ('npl_status', models.TextField(blank=True, max_length=255)),
                ('lon', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('address', models.TextField(blank=True, max_length=155)),
                ('tract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viz.IncomeTract')),
            ],
        ),
    ]
